### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by Ximoi** [liudaizong/F2Net#3]
Thank you for your job on video segmentation. Now I try to follow your work, and can i get your test.py for testing the trained model. Thanks again.

**Comment by liudaizong** [comment]
> Thank you for your job on video segmentation. Now I try to follow your work, and can i get your test.py for testing the trained model. Thanks again.

Hi, I have uploaded the test.py file in this repository. You can edit it yourself and then test your trained model.

**Comment by Ximoi** [comment]
> > Thank you for your job on video segmentation. Now I try to follow your work, and can i get your test.py for testing the trained model. Thanks again.
> 
> Hi, I have uploaded the test.py file in this repository. You can edit it yourself and then test your trained model.

Thanks again.
